spring.application.name=resume
server.port=9090
spring.profiles.active=secret

resume.access-password=${RESUME_ACCESS_PASSWORD:changeme}
resume.access-token=${RESUME_ACCESS_TOKEN:}

spring.mongodb.uri=${SPRING_MONGODB_URI:}